#
#
include ../libsx_defs

# the object files which the program depends on
OBJS       = main.o callbacks.o controlbox.o

cbox : $(OBJS)
	$(CC) -o $@ $(OBJS) $(LIBS)


# main.o depends on main.c (of course) and main.h and callbacks.h
main.o : main.c main.h callbacks.h controlbox.h

callbacks.o : callbacks.c

controlbox.o : controlbox.c controlbox.c

clean :
	rm -f *.o *~ core skel cbox

