#
#
include ../libsx_defs

# the object files which the program depends on
OBJS       = main.o callbacks.o

demo3 : $(OBJS)
	$(CC) -o demo3 $(OBJS) $(LIBS)


# main.o depends on main.c (of course) and main.h and callbacks.h
main.o : main.c main.h callbacks.h

callbacks.o : callbacks.c main.h


clean :
	rm -f *.o *~ core demo3

